// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Token struct {
	HashedToken []byte    `json:"hashed_token"`
	UserID      int64     `json:"user_id"`
	Scope       string    `json:"scope"`
	Expiry      time.Time `json:"expiry"`
}

type User struct {
	ID             int64     `json:"id"`
	CreatedAt      time.Time `json:"created_at"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword []byte    `json:"hashed_password"`
	Activated      bool      `json:"activated"`
	Version        int32     `json:"version"`
}
