// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(name, email, hashed_password, activated)
VALUES ($1,$2,$3,$4)
RETURNING id, created_at, version
`

type CreateUserParams struct {
	Name           string `json:"name"`
	Email          string `json:"email"`
	HashedPassword []byte `json:"hashed_password"`
	Activated      bool   `json:"activated"`
}

type CreateUserRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	Version   int32     `json:"version"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.HashedPassword,
		arg.Activated,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Version)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, name, email, hashed_password, activated, version FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Activated,
		&i.Version,
	)
	return i, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT id, created_at, name, email, hashed_password, activated, version FROM users
WHERE email = $1
`

func (q *Queries) GetUserEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Activated,
		&i.Version,
	)
	return i, err
}

const getUserFromToken = `-- name: GetUserFromToken :one
select users.id, users.created_at, users.name, users.email, users.hashed_password, users.activated, users.version from tokens join users on users.id = tokens.user_id
where tokens.hashed_token = $1 and tokens.scope = $2 and tokens.expiry > $3
`

type GetUserFromTokenParams struct {
	HashedToken []byte    `json:"hashed_token"`
	Scope       string    `json:"scope"`
	Expiry      time.Time `json:"expiry"`
}

func (q *Queries) GetUserFromToken(ctx context.Context, arg GetUserFromTokenParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromToken, arg.HashedToken, arg.Scope, arg.Expiry)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.Activated,
		&i.Version,
	)
	return i, err
}
